### ISSUE TITLE
Domain Expertise beyond "CF"?

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf/areas-of-contribution#24]
The domain of our products is larger than "Cloud Foundry."  Within the Pivotal Cloud R&D organization we're now shipping products that aren't directly tied to "Cloud Foundry" and we're finding that our engineers impact teams and customers through their expertise in domains such as Kubernetes and Istio.

Is there value in keeping the letters "CF" in [this skill area](https://github.com/pivotal-cf/areas-of-contribution/blob/master/cf-domain-expertise.md)?

**Comment by ctaymor** [comment]
I agree removing the letters CF might be helpful. I have reports who have been working on K8s for a while now, and are developing significant domain expertise there. There currently isn't a way to capture that contribution, but I'm planning to use the "CF Domain Expertise" section to capture their K8s domain expertise anyways, just ignoring the "CF" part.
