### ISSUE TITLE
Turning this repo into a google form

### ISSUE THREAD

**Issue by mrosecrance** [pivotal-cf/areas-of-contribution#28]
I might be misunderstanding how this repo is meant to be used or missing a setup doc but it's not obvious to me how to use the `regenerate` tool to create a google form to put in front of someone or how I would go about applying it's output to a form I already have. 

Not sure if this is an appropriate issue for this repo or should be spelled out in a different channel so feel free to push back.

**Comment by rosenhouse** [comment]
Hi @mrosecrance:

We're actively developing the tools at the moment, and don't yet have automation for managers.

Instead, for new reports, we recommend that you make a copy of a Template Form and Template Spreadsheet.  You'll find detailed instructions [in this google doc](https://docs.google.com/document/d/1oMZCSawijIcKRm9W2q_TuqJobLiTZQ775dH02QOTDCs/edit) and more resources for managers in [this private repo](https://github.com/pivotal-cf/feedback-and-evaluation).

**Comment by hiremaga** [comment]
@rosenhouse have you considered cutting a release of this repo for v2-rc1 with links to a corresponding version of the template form & spreadsheet? I vaguely recall hearing you say something along these lines in one of our conversations.

**Comment by rosenhouse** [comment]
Yeah, cutting a release is definitely part of the plan, but I wouldn't ask anyone to wait on it before collecting feedback.

**Comment by rosenhouse** [comment]
We now have documentation for this stuff.

In short, there are:
- The tools: Feedback Form and Heatmap Spreadsheet, which are now at version 2.
- The skill definitions: the contents of this repo, for which we've just released [v0.2.0](https://github.com/pivotal-cf/areas-of-contribution/releases/tag/0.2.0)

Documentation:
- [User Guide v2](https://docs.google.com/document/d/17fJITTVIjEEzhkdE3TuPPBfpdX_W3esxwj6cjKI_5zQ/edit) describes how to create or upgrade to version 2 tools (Form and Sheet) for a report
- [Migration Guide](https://docs.google.com/document/d/16oNRUupxmx9lypyhd1FPAPZCZJ8w33mWTQMiu1LNLTY/edit) describes how to migrate a v2 Form and Sheet from one version of this repo to another, e.g. from release 0.1.1 (the starting point) to [release 0.2.0](https://github.com/pivotal-cf/areas-of-contribution/releases/tag/0.2.0)
