### ISSUE TITLE
What is "Can onboard pairs into well-defined stories"?

### ISSUE THREAD

**Issue by ctaymor** [pivotal-cf/areas-of-contribution#31]
I was going over the feedback form with someone, and they asked what "Can onboard pairs into well-defined stories" (P2) meant, and how it differed from "Is comfortable with carrying context on well-defined stories" (a P1 skill). I wasn't sure myself.

I tend to think of it as "can not just do a minimal job carrying context, such that your team is ok with you carrying context when rotating pairs, but also give more of this history of how the story evolved, and where you're going". Sort of a "keeping context **well**".

I'd like to clarify the language on this skill, but first I want to understand how others interpret this skill, to make sure I'm in alignment with other managers.

**Comment by hiremaga** [comment]
I've heard the idea of an _arc_ described by @rosenhouse, perhaps in reference to conversations with @rnandi. I wonder if these two skills are intended to be part of an arc.

**Comment by ctaymor** [comment]
Yes, I think of these as an arc too.

**Comment by rosenhouse** [comment]
@ctaymor We think we've addressed this in #47 but please respond if you feel otherwise.

**Comment by ctaymor** [comment]
That's a great improvement. 👍
