### ISSUE TITLE
Advanced version of "Actively leaves space for others to share their ideas"?

### ISSUE THREAD

**Issue by ctaymor** [pivotal-cf/areas-of-contribution#32]
I'd like to propose either the addition of a more advanced version of "Actively leaves space for others to share their ideas" or that we move it to be an advanced skill. I've observed (both as a manager and a engineer) that this is a very easy skill for the majority of new pivots because they don't have any opinions yet, or the confidence to share them.
However, it is a very hard skill for many pivots with a lot of experience. The impact of pivots with lots of experience and opinions leaving space for others is far greater than when new pivots do it, and I think it's crucial. I also don't think we capture that more advanced skill.
I'm not sure it's a P1 skill at all, because I haven't seen P1s who struggle with this. So my initial proposal is to move the skill to P3. However, I think it's valuable for all pivots to be thinking about, so I'm also open to adding a version of this skill at P3 which is worded slightly differently.

**Comment by ctaymor** [comment]
Upon further reflection, I'm going to propose that "Actively leaves space for others to share their ideas" is a P2 skill. I think most P1s are learning to share their ideas still. I can't think of a time I saw a P1 monopolizing the room. The followup skill in this arc would be a P3 skill of "Actively works to ensure quieter teammates have room to share and get recognition for their ideas."

There might be a follow up P4 (helping others do it) skill in this arc of "Coaches pivots on how to facilitate conversations and meetings that allow other quieter teammates to share and get recognition for their ideas"

P2 -> Doing it yourself
P3 -> Doing it well, at the team level
P4 -> Helping others do it

**Comment by rosenhouse** [comment]
Merged #35, @ctaymor should we keep this issue open?

**Comment by ctaymor** [comment]
Let's close it.
