### ISSUE TITLE
Tool for Managers: Validate feedback spreadsheet and form matches expected version of skills

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf/areas-of-contribution#33]
As a manager, given I have a spreadsheet or form where I messed-up a skill definition (e.g. fat-fingered some text somewhere), I'd like to be informed of this error and have an option to fix it.

Note: We wanted to do this as part of the soon-to-wrap-up manager initiative, but didn't complete it.

**Comment by rnandi** [comment]
We did it 🎉
