### ISSUE TITLE
Knowing when to put things down

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf/areas-of-contribution#37]
This is an important skill.  Maybe an arc?

- p1: is comfortable letting go of a priority that they have worked on
- p2: recognizes when their pair or team would benefit from cutting scope and advocates for it
- p3: effectively advocates to anchor/PM to cut scope or stop efforts that no longer align with team's priorities
- p4: collaborates with leadership to identify cross-team scope that should be cut, builds alignment with stakeholders, and drives it to completion
- p5: regularly collaborates with leadership to align engineering efforts with strategic needs of the organization

**Comment by rnandi** [comment]
@rosenhouse Do you think identifying what scope to cut could be treated as an implementation detail of having the outcome of helping teams understand their priorities and being aligned with them in their day-to-day work? In which case, should we try to word the contributions more in terms of the outcome of being aligned with priorities?

Additionally, one thing to keep in mind when thinking about wording here is to _not_ incentivize advocating for cutting scope in a way that creates unhealthy conflict within the team, with PMs, and/or with leadership.

p1: Looks good
p2: Help my pair (or small team) feel comfortable cutting scope from a large story or small track
p3: Help my team and leadership agree upon the right scope to cut from a large track or product
p4: Collaborates across teams and stakeholders to cut scope and re-align with Program priorities
p5: Looks good

Thanks @totherme for pairing with me on the response!

**Comment by rosenhouse** [comment]
@rupa and @totherme:

Thanks for the feedback.  Your general suggestions make sense.  The wording you proposed for P2 and P3 seems to remove the part about *recognizing the opportunity to cut-scope*.  I think that recognition is important, and want to keep that in.

I've opened a PR #38 that takes (almost?) everything else you suggested but retains that aspect of my original definitions.

Take a look!
