### ISSUE TITLE
Which west coast?

### ISSUE THREAD

**Issue by bruce-ricard** [pivotal-cf/areas-of-contribution#52]
The description of the repo is not very inclusive of non US people.

If you live in [Niigata](https://www.google.com/maps/place/Niigata,+Japan/@37.8404185,138.8848941,11z/data=!3m1!4b1!4m13!1m7!3m6!1s0x34674e0fd77f192f:0xf54275d47c665244!2sJapan!3b1!8m2!3d36.204824!4d138.252924!3m4!1s0x5ff4c5c255c7c0f7:0xf1509bcbc990230d!8m2!3d37.9160343!4d139.0361023), are you on the west coast?

**Comment by njbennett** [comment]
Should we update this to "Skills for CF Engineers on the West Coast of North America" @rosenhouse ? I don't think I have edit access here.

**Comment by rosenhouse** [comment]
Pull requests are welcome

**Comment by rainmaker** [comment]
We've modified the header to make it clearer 👍
