### ISSUE TITLE
CF Domain Expertise: "Is learning about how other teams/downstream consumers/customers use their product"

### ISSUE THREAD

**Issue by benmoss** [pivotal-cf/areas-of-contribution#8]
This one seems very vague and almost too passive. It's hard to imagine that anyone on the team isn't in some way learning how other teams/customers are using their product just by virtue of listening in meetings etc. Maybe if it was "Has sound knowledge about how" or something it would feel a little easier to say when someone is missing this skill.

https://github.com/pivotal-cf/areas-of-contribution/blame/bbd2f84477458de6f208ada3925b0961537f27bc/cf-domain-expertise.md#L26

**Comment by utako** [comment]
"displays knowledge..." or "asks questions about..." would be more observable than "is learning."

**Comment by rosenhouse** [comment]
[related tracker story](https://www.pivotaltracker.com/story/show/157229324)

**Comment by rosenhouse** [comment]
@benmoss Thanks for raising this issue.

We're starting to re-invest in this repo, and the first priority is to enable a pull-request-based contribution model for changing the content here.  We've put a bit more detail about our plans [this roadmap](https://github.com/pivotal-cf/areas-of-contribution/blob/master/CONTRIBUTING.md#roadmap).

We don't have anything actionable yet. But once we've made progress on that roadmap, we intend to respond again here with pointers to a contribution workflow that you or others could follow to address this issue.

Thanks for your patience!
